# Generated by Django 4.0.5 on 2022-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del director', max_length=64)),
                ('apellido', models.CharField(help_text='Apellido del director', max_length=64)),
                ('nacimiento', models.PositiveIntegerField(help_text='Año de nacimiento')),
                ('biografia', models.TextField(help_text='Biografia del director')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del genero', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo de la pelicula', max_length=64)),
                ('descripcion', models.TextField(help_text='Descripción de la pelicula', max_length=256)),
                ('duracion', models.PositiveIntegerField(help_text='Duración de la pelicula')),
                ('estreno', models.PositiveIntegerField(help_text='Año de estreno')),
                ('director', models.ForeignKey(help_text='Director de la pelicula', on_delete=django.db.models.deletion.CASCADE, to='peliculas.director')),
                ('genero', models.ManyToManyField(help_text='Genero de la pelicula', to='peliculas.genero')),
            ],
        ),
    ]
